/** Random flavor words shown when response completes (e.g., "Baked for 1:23"). */
export const COMPLETION_FLAVOR_WORDS = [
  'Baked',
  'Cooked',
  'Crunched',
  'Brewed',
  'Crafted',
  'Forged',
  'Conjured',
  'Whipped up',
  'Stirred',
  'Simmered',
  'Toasted',
  'Sautéed',
  'Finagled',
  'Marinated',
  'Distilled',
  'Fermented',
  'Percolated',
  'Steeped',
  'Roasted',
  'Cured',
  'Smoked',
  'Cogitated',
] as const;

/** Random flavor texts shown while Claude is thinking. */
export const FLAVOR_TEXTS = [
  // Klassisch
  'Denke nach...',
  'Überlege...',
  'Verarbeite...',
  'Analysiere...',
  'Wäge ab...',
  'Bin dran...',
  'Einen Moment...',
  'Läuft...',
  // Nachdenklich
  'Grüble...',
  'Sinniere...',
  'Reflektiere...',
  'Lass mich überlegen...',
  'Hmm...',
  'Wäge Optionen ab...',
  'Sammle Gedanken...',
  'Sortiere Gedanken...',
  // Verspielt
  'Braue Ideen...',
  'Verbinde die Punkte...',
  'Setze Gedanken zusammen...',
  'Fahre Neuronen hoch...',
  'Lade Brillanz...',
  'Befrage das Orakel...',
  'Beschwöre Wissen...',
  'Zähme Ideen...',
  'Hüte Gedanken...',
  'Jongliere Konzepte...',
  'Entwirre das...',
  'Puzzle es zusammen...',
  // Gemütlich
  'Nippe am Kaffee...',
  'Wärme mich auf...',
  'Mache es mir gemütlich...',
  'Richte mich ein...',
  'Koche Tee...',
  'Hole einen Snack...',
  // Technisch
  'Parse...',
  'Kompiliere Gedanken...',
  'Inferenz läuft...',
  'Befrage die Leere...',
  'Defragmentiere Gehirn...',
  'Alloziere Speicher...',
  'Optimiere...',
  'Indexiere...',
  'Synchronisiere Neuronen...',
  // Zen
  'Atme...',
  'Finde Klarheit...',
  'Bündle Fokus...',
  'Zentriere mich...',
  'Richte Chakren aus...',
  'Meditiere darüber...',
  // Verspielt-mystisch
  'Frage die Sterne...',
  'Lese Teeblätter...',
  'Schüttle die Magic 8-Ball...',
  'Konsultiere alte Schriftrollen...',
  'Dekodiere die Matrix...',
  'Lausche dem Äther...',
  'Blicke in den Abgrund...',
  'Kanalisiere den Kosmos...',
  // Aktion
  'Tauche ein...',
  'Krempel die Ärmel hoch...',
  'Lege los...',
  'Packe es an...',
  'Bin am Fall...',
  'Ermittle...',
  'Erkunde...',
  'Grabe tiefer...',
  // Locker
  'Kurz durchhalten...',
  'Gleich soweit...',
  'Nur eine Sekunde...',
  'Wirke meine Magie...',
  'Fast fertig...',
  'Gib mir einen Moment...',
];
